### ISSUE TITLE
SyntaxError on calling dotnet-new from command line

### ISSUE THREAD

**Issue by kaitlynbrown** [ServiceStack/servicestack-cli#2]
```
C:\Users\Katie>dotnet-new
C:\Users\Katie\AppData\Roaming\npm\node_modules\@servicestack\cli\node_modules\request\node_modules\hawk\node_modules\boom\lib\index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Katie\AppData\Roaming\npm\node_modules\@servicestack\cli\node_modules\request\node_modules\hawk\lib\index.js:5:33)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by mythz** [comment]
Maybe you have an old version of node? What does `node -v` say?

**Comment by kaitlynbrown** [comment]
v0.12.2

**Comment by kaitlynbrown** [comment]
I guess I haven't updated node on this machine in a really long time! It works now, thank you :)
